- name: Renommer le binaire promtail
  ansible.builtin.command: mv /usr/local/bin/promtail-linux-amd64 /usr/local/bin/promtail
  args:
    creates: /usr/local/bin/promtail

- name: Créer le service systemd pour Promtail
  ansible.builtin.copy:
    dest: /etc/systemd/system/promtail.service
    content: |
      [Unit]
      Description=Promtail service
      After=network.target

      [Service]
      User=promtail
      Group=promtail
      ExecStart=/usr/local/bin/promtail -config.file=/etc/promtail/promtail-config.yaml
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target

- name: Déployer le fichier de config
  ansible.builtin.template:
    src: promtail-config.yaml
    dest: /etc/promtail/promtail-config.yaml
    owner: promtail
    group: promtail
    mode: '0644'

- name: Redémarrer et activer Promtail
  ansible.builtin.systemd:
    name: promtail
    enabled: yes
    state: restarted
    daemon_reload: yes
