---
galaxy_info:
  author: ton_nom
  description: Installe et configure Grafana
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal

dependencies: []