- name: Renommer le binaire Loki
  ansible.builtin.command: mv /usr/local/bin/loki-linux-amd64 /usr/local/bin/loki
  args:
    creates: /usr/local/bin/loki

- name: Créer les répertoires de données pour Loki
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - /var/log/loki
    - /var/log/loki/index
    - /var/log/loki/boltdb-cache
    - /var/log/loki/chunks


- name: Créer le dossier de conf de Loki
  ansible.builtin.file:
    path: /etc/loki
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copier la configuration de Loki
  ansible.builtin.template:
    src: loki-config.yaml
    dest: /etc/loki/loki-config.yaml
    mode: '0644'

- name: Créer le service systemd Loki
  ansible.builtin.copy:
    dest: /etc/systemd/system/loki.service
    content: |
      [Unit]
      Description=Loki service
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/loki -config.file=/etc/loki/loki-config.yaml
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Redémarrer Loki
  ansible.builtin.systemd:
    name: loki
    enabled: yes
    state: restarted
    daemon_reload: yes
